name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint

    - name: AEM Code Sync
      uses: adobe/aem-code-sync@v1
      with:
        aem_project_id: ${{ secrets.AEM_PROJECT_ID }}